var searchData=
[
  ['k',['k',['http://en.cppreference.com/w/cpp/numeric/random/negative_binomial_distribution/params.html',1,'std::negative_binomial_distribution']]],
  ['kappa_5ftimes_5fp_5fover_5frho_5fsquared_5ffrom_5fdensity',['kappa_times_p_over_rho_squared_from_density',['../classEquationsOfState_1_1EquationOfState_3_01IsRelativistic_00_011_01_4.html#a818842159c52f5c00f605dd246069d0d',1,'EquationsOfState::EquationOfState&lt; IsRelativistic, 1 &gt;::kappa_times_p_over_rho_squared_from_density(const Scalar&lt; double &gt; &amp;) const noexcept=0'],['../classEquationsOfState_1_1EquationOfState_3_01IsRelativistic_00_011_01_4.html#aa0e265e9d3118a90ec9033e1bca7f3e0',1,'EquationsOfState::EquationOfState&lt; IsRelativistic, 1 &gt;::kappa_times_p_over_rho_squared_from_density(const Scalar&lt; DataVector &gt; &amp;) const noexcept=0']]],
  ['kappa_5ftimes_5fp_5fover_5frho_5fsquared_5ffrom_5fdensity_5fand_5fenergy',['kappa_times_p_over_rho_squared_from_density_and_energy',['../classEquationsOfState_1_1EquationOfState_3_01IsRelativistic_00_012_01_4.html#adbb6355adcecb57f0b6730d155ef5fd3',1,'EquationsOfState::EquationOfState&lt; IsRelativistic, 2 &gt;::kappa_times_p_over_rho_squared_from_density_and_energy(const Scalar&lt; double &gt; &amp;, const Scalar&lt; double &gt; &amp;) const noexcept=0'],['../classEquationsOfState_1_1EquationOfState_3_01IsRelativistic_00_012_01_4.html#a15b27516c915c161dff5bb5880aedbc2',1,'EquationsOfState::EquationOfState&lt; IsRelativistic, 2 &gt;::kappa_times_p_over_rho_squared_from_density_and_energy(const Scalar&lt; DataVector &gt; &amp;, const Scalar&lt; DataVector &gt; &amp;) const noexcept=0']]],
  ['kerr_5fhorizon_5fradius',['kerr_horizon_radius',['../namespacegr_1_1Solutions.html#af906e2ce2c0f647fa2fa960d49e637e5',1,'gr::Solutions']]],
  ['kerrhorizon',['KerrHorizon',['../structintrp_1_1OptionHolders_1_1KerrHorizon.html',1,'intrp::OptionHolders::KerrHorizon'],['../structintrp_1_1OptionTags_1_1KerrHorizon.html',1,'intrp::OptionTags::KerrHorizon&lt; InterpolationTargetTag &gt;'],['../structintrp_1_1Tags_1_1KerrHorizon.html',1,'intrp::Tags::KerrHorizon&lt; InterpolationTargetTag &gt;'],['../structintrp_1_1Actions_1_1KerrHorizon.html',1,'intrp::Actions::KerrHorizon&lt; InterpolationTargetTag, Frame &gt;']]],
  ['kerrschild',['KerrSchild',['../classgr_1_1Solutions_1_1KerrSchild.html',1,'gr::Solutions']]],
  ['kerrschildcoords',['KerrSchildCoords',['../classgr_1_1KerrSchildCoords.html',1,'gr']]],
  ['key_5fcomp',['key_comp',['http://en.cppreference.com/w/cpp/container/map/key_comp.html',1,'std::map::key_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/key_comp.html',1,'std::multimap::key_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/key_comp.html',1,'std::multiset::key_comp()'],['http://en.cppreference.com/w/cpp/container/map/key_comp.html',1,'std::pmr::map::key_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/key_comp.html',1,'std::pmr::multimap::key_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/key_comp.html',1,'std::pmr::multiset::key_comp()'],['http://en.cppreference.com/w/cpp/container/set/key_comp.html',1,'std::pmr::set::key_comp()'],['http://en.cppreference.com/w/cpp/container/set/key_comp.html',1,'std::set::key_comp()']]],
  ['key_5feq',['key_eq',['http://en.cppreference.com/w/cpp/container/unordered_map/key_eq.html',1,'std::pmr::unordered_map::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_multimap/key_eq.html',1,'std::pmr::unordered_multimap::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_multiset/key_eq.html',1,'std::pmr::unordered_multiset::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_set/key_eq.html',1,'std::pmr::unordered_set::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_map/key_eq.html',1,'std::unordered_map::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_multimap/key_eq.html',1,'std::unordered_multimap::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_multiset/key_eq.html',1,'std::unordered_multiset::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_set/key_eq.html',1,'std::unordered_set::key_eq()'],['../classFixedHashMap.html#ae839b3d9b5ab8ec48e8dccc94337b582',1,'FixedHashMap::key_eq()']]],
  ['keys_5fof',['keys_of',['../group__UtilitiesGroup.html#ga495b431a620b10beb24f1afc90b77e20',1,'keys_of(const std::unordered_map&lt; K, V, H &gt; &amp;m):&#160;StdHelpers.hpp'],['../group__UtilitiesGroup.html#gaf707b57628e9425c91d92eb278a52c99',1,'keys_of(const std::map&lt; K, V, C &gt; &amp;m):&#160;StdHelpers.hpp']]],
  ['kilo',['kilo',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio.html',1,'std']]],
  ['knuth_5fb',['knuth_b',['http://en.cppreference.com/w/cpp/numeric/random/shuffle_order_engine.html',1,'std::knuth_b'],['http://en.cppreference.com/w/cpp/numeric/random/shuffle_order_engine/shuffle_order_engine.html',1,'std::knuth_b::knuth_b()']]],
  ['komissarovshock',['KomissarovShock',['../classgrmhd_1_1Solutions_1_1KomissarovShock.html',1,'grmhd::Solutions']]],
  ['krivodonova_3c_20volumedim_2c_20tmpl_3a_3alist_3c_20tags_2e_2e_2e_20_3e_20_3e',['Krivodonova&lt; VolumeDim, tmpl::list&lt; Tags... &gt; &gt;',['../classLimiters_1_1Krivodonova_3_01VolumeDim_00_01tmpl_1_1list_3_01Tags_8_8_8_01_4_01_4.html',1,'Limiters']]],
  ['krylovsubspacebasis',['KrylovSubspaceBasis',['../structLinearSolver_1_1Tags_1_1KrylovSubspaceBasis.html',1,'LinearSolver::Tags']]]
];
